"""
Prometheus metrics for MedAssist-GenAI. Exposed at GET /metrics (see
serving/api.py) for scraping by a Prometheus server, which Grafana then
reads for the dashboard defined in monitoring/grafana_dashboard.json.
"""
from prometheus_client import Counter, Histogram, Gauge

# --- Request-level metrics ---
REQUEST_COUNT = Counter(
    "medassist_requests_total", "Total chat requests", ["endpoint", "status"]
)
REQUEST_LATENCY = Histogram(
    "medassist_request_latency_seconds", "End-to-end request latency",
    buckets=(0.1, 0.25, 0.5, 1, 2, 5, 10, 20, 30, 60),
)

# --- Safety-specific metrics (arguably the most important dashboard panel
#     for this domain) ---
EMERGENCY_TRIGGERED = Counter(
    "medassist_emergency_responses_total", "Times the emergency short-circuit fired"
)
INSUFFICIENT_EVIDENCE_COUNT = Counter(
    "medassist_insufficient_evidence_total",
    "Times RAG returned no passages above the relevance floor",
)
REFUSAL_COUNT = Counter(
    "medassist_refusals_total", "Times the agent refused a request"
)

# --- RAG-specific metrics ---
RETRIEVAL_LATENCY = Histogram(
    "medassist_retrieval_latency_seconds", "Time spent in hybrid retrieval + rerank"
)
RETRIEVAL_RELEVANCE_SCORE = Histogram(
    "medassist_retrieval_top_relevance_score",
    "Top reranked passage relevance score per query",
    buckets=(0.0, 0.1, 0.2, 0.3, 0.35, 0.5, 0.7, 0.9, 1.0),
)

# --- LLM / vLLM metrics ---
LLM_LATENCY = Histogram("medassist_llm_latency_seconds", "vLLM generation latency")
LLM_TOKENS_GENERATED = Counter(
    "medassist_llm_tokens_generated_total", "Total tokens generated by the LLM"
)
ACTIVE_LORA_ADAPTER = Gauge(
    "medassist_active_lora_adapter_info",
    "Which adapter version is currently serving (1=active)",
    ["adapter_version"],
)

# --- Agent / tool metrics ---
TOOL_CALL_COUNT = Counter(
    "medassist_tool_calls_total", "Tool invocations by tool name", ["tool_name"]
)
AGENT_ITERATIONS = Histogram(
    "medassist_agent_iterations", "Number of tool-call loops per request",
    buckets=(1, 2, 3, 4, 5, 6),
)
